import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';
import { getValidSessionByToken } from '../../database/sessions';
import { getUserBySessionToken } from '../../database/users';

export const metadata = {
  title: 'Admin page',
  description: 'Generated by create next app',
};

export default async function AnimalsPage() {
  // Task: Add redirect to home if user is logged in
  // 1. Checking if the sessionToken cookie exists
  const sessionTokenCookie = cookies().get('sessionToken');
  // 2. Check if the sessionToken cookie is still valid
  const session =
    sessionTokenCookie &&
    (await getUserBySessionToken(sessionTokenCookie.value));

  //  Query your database to check if this user is admin

  // 3. If the sessionToken cookie is invalid or doesn't exist, redirect to login with returnTo
  if (!session) redirect('/login?returnTo=/(auth)/admin');
  if (session.isAdmin === false) redirect('/404');

  // 4. If the sessionToken cookie is valid, allow access to admin page
  return <div className="mt-8">Admin Page</div>;
}
