import './globals.css';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { ReactNode } from 'react';
import { getUserBySessionToken } from '../database/users';
import LogoutButton from './(auth)/logout/LogoutButton';

/* import CookieBanner from './CookieBanner'; */

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: { default: 'Home page | cryEx', template: '%s | cryEx' },
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

export default async function RootLayout(props: Props) {
  // Task: Display the logged in user's username in the navigation bar and hide the login and register links depending on whether the user is logged in or not
  // 1. Checking if the sessionToken cookie exists
  // 2. Get the current logged in user from the database using the sessionToken value
  // 3. Make decision whether to show the login and register links or not

  // 1. Checking if the sessionToken cookie exists
  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken');

  const user =
    sessionToken && (await getUserBySessionToken(sessionToken.value));

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <CookieBanner /> */}
        <div className="navbar bg-base-100">
          <a className="btn btn-ghost normal-case text-xl">cryEx</a>
          <div className="btn-group">
            <Link className="btn btn-active" href="/">
              Home
            </Link>
            <Link className="btn" href="/admin">
              Admin
            </Link>
            <Link className="btn" href="/notes">
              Notes
            </Link>
          </div>

          <div>
            {user ? (
              <>
                <div>Welcome {user.username}!</div>
                <LogoutButton className="btn" />
              </>
            ) : (
              <>
                <Link className="btn" href="/register">
                  Register
                </Link>
                <Link className="btn" href="/login">
                  Login
                </Link>
              </>
            )}
          </div>
        </div>

        {props.children}
      </body>
    </html>
  );
}
